### PR TITLE
Upgrade ruamel.yaml configurations for latest version

### LINKED ISSUE #82: disconnected-csv github action failing - ruamel.yaml round_trip_load deprecated
There appears to be a deprecated function in ruamel.yaml python package causing release PRs to fail.

The error: https://github.com/redhat-cop/vault-config-operator/actions/runs/6658073094/job/18094709725

```sh
Traceback (most recent call last):
  File "//add_related_image.py", line 19, in <module>
    csv = yaml.round_trip_load(stream)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/github/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1113, in round_trip_load
    error_deprecation('round_trip_load_all', 'load')
  File "/home/github/lib/python3.11/site-packages/ruamel/yaml/main.py", line 1025, in error_deprecation
    raise AttributeError(s, name=None)
AttributeError: 
"round_trip_load_all()" has been removed, use

  yaml = YAML()
  yaml.load(...)
```

Notes:
Deprecation line: https://github.com/redhat-cop/github-actions/blob/master/disconnected-csv/add_related_image.py#L19
Latest ruamel.yaml package appears to be 0.18.2
Docs: https://yaml.readthedocs.io/en/latest/api/

### PR DESCRIPTION
**Pull request by sabre1041**
#### What is this PR About?
Upgrade ruamel.yaml configurations in disconnected-csv action for latest version to resolve #82 

cc: @redhat-cop/github-actions

### CODE REVIEW

**Comment by raffaelespazzoli** [comment]
LGTM, please merge.

**Comment by raffaelespazzoli** [comment]
and please cut a new release.

**Comment by sabre1041** [comment]
@garethahealy @jacobsee can you review this?

**Review by garethahealy — APPROVED** [review]

**Pull request merged**
