### PR TITLE
updating chart-repo-pr-action usage documentation

### PR DESCRIPTION
**Pull request by deweya**
Making small adjustment to chart-repo-pr-action readme. Needed to update the reference to redhat-cop/github-actions/chart-repo-pr-action@master

cc: @redhat-cop/github-actions

### CODE REVIEW

**Review by pabrahamsson — COMMENTED** [review]
Thanks @deweya, should we create a new release of this repo so that we aren't referencing `master`?

**Comment by deweya** [comment]
Good point @pabrahamsson , yeah we probably should. Looks like `v2` is the last tag, should I update this to reference `v3`?

**Comment by pabrahamsson** [comment]
yes I think that sounds good @deweya, I will take care of cutting the new release.

**Comment by deweya** [comment]
Cool @pabrahamsson , updated to use v3

**Review by pabrahamsson — APPROVED** [review]
LGTM

**Comment by pabrahamsson** [comment]
v3 has been released @deweya

**Pull request merged**
