### PR TITLE
added link to rh-actions s2i

### PR DESCRIPTION
**Pull request by garethahealy**
#### What is this PR About?
Since the redhat-actions repo also provides an s2i, which works on multiple platforms, think we should point people to that one.

cc: @redhat-cop/github-actions

### CODE REVIEW

**Comment by garethahealy** [comment]
CC @pabrahamsson @jacobsee

**Review by pabrahamsson — COMMENTED** [review]
LGTM @garethahealy 
Is the CI expected to pass? Can't see how this change will fail the test

**Comment by garethahealy** [comment]
@pabrahamsson ; yep, CI is expected to fail: https://github.com/redhat-cop/github-actions/issues/24

**Review by pabrahamsson — APPROVED** [review]
LGTM

**Pull request merged**
